services:
  backend:
    build: backend
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=track-rooms
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  # In Docker
  # - TEST_POSTGRES_URI=postgres://user:password@postgres/

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=track-rooms
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: