version: '3.8'
services:
  # In Docker
  # - TEST_POSTGRES_URI=postgres://user:password@postgres/

  postgres:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=track-rooms
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: